sudo: false
language: erlang
otp_release:
  - 18.2.3
  - 18.2.2
  - 18.2.1
  - 18.2
  - 18.1.5
  - 18.1.4
  - 18.1.3
  - 18.1.2
  - 18.1.1
  - 18.1
  - 18.0.3
  - 18.0.2
  - 18.0.1
  - 18.0
  - 17.5.6.2
  - 17.5.6.1
  - 17.5.6
  - 17.5.5
  - 17.5.4
  - 17.5.3
  - 17.5.2
  - 17.5.1
  - 17.5
  - 17.4.1
  - 17.4
  - 17.3.4
  - 17.3.3
  - 17.3.2
  - 17.3.1
  - 17.3
  - 17.2.2
  - 17.2.1
  - 17.2
  - 17.1.2
  - 17.1.1
  - 17.1
  - 17.0.2
  - 17.0.1
  - 17.0
  - R16B03-1
  - R16B03
  - R16B02
  - R16B01
  - R16B
  - R15B03-1
  - R15B03
  - R15B02
  - R15B01
  - R15B
  - R14B04
  - R14B03
  - R14B02
# R14B01 crashed during build on travis-ci. Therefore, there's no
# build to use on travis-ci. See:
# https://s3.amazonaws.com/archive.travis-ci.org/jobs/69906408/log.txt
# and
# https://github.com/travis-ci/travis-ci/issues/2757#issuecomment-119235879
#  - R14B01
  - R14B
  - R13B04
  - R13B03
before_script:
  - hostname -f
  - cc -v
  - ld -v
script: "make travis"
